# Generated by Django 4.2.7 on 2024-06-10 11:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renthouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpost',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ownerpostownercomment',
            name='comment_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ownerpostusercomment',
            name='comment_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='userpostownercomment',
            name='comment_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='userpostusercomment',
            name='comment_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
