# Generated by Django 4.2.7 on 2024-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthouse', '0003_houseowner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
