# Generated by Django 4.0.6 on 2024-06-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthouse', '0004_alter_houseimage_image_alter_roomimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseowner',
            name='is_houseowner',
            field=models.BooleanField(default=True),
        ),
    ]
