# Generated by Django 4.0.6 on 2024-06-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthouse', '0005_houseowner_is_houseowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseowner',
            name='is_houseowner',
        ),
        migrations.AddField(
            model_name='user',
            name='is_houseowner',
            field=models.BooleanField(default=False),
        ),
    ]
