# Generated by Django 4.0.6 on 2024-06-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renthouse', '0006_remove_houseowner_is_houseowner_user_is_houseowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostownercomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userpostownercomment',
            name='post_comment',
        ),
        migrations.DeleteModel(
            name='OwnerPostOwnerComment',
        ),
        migrations.DeleteModel(
            name='UserPostOwnerComment',
        ),
    ]
